//! IRC error response code definitions (ERR_* numerics).
//!
//! This module contains the enum variants for error IRC server responses.

// This file is auto-generated from response/mod.rs refactoring.
// All ERR_* (error) numeric codes.

use super::Response;

impl Response {
    /// Returns all ERR_* (error) response variants from code mapping.
    ///
    /// Used by `from_code()` to map numeric codes to Response enum variants.
    pub(super) fn from_error_code(code: u16) -> Option<Response> {
        Some(match code {
            400 => Response::ERR_UNKNOWNERROR,
            401 => Response::ERR_NOSUCHNICK,
            402 => Response::ERR_NOSUCHSERVER,
            403 => Response::ERR_NOSUCHCHANNEL,
            404 => Response::ERR_CANNOTSENDTOCHAN,
            405 => Response::ERR_TOOMANYCHANNELS,
            406 => Response::ERR_WASNOSUCHNICK,
            407 => Response::ERR_TOOMANYTARGETS,
            408 => Response::ERR_NOSUCHSERVICE,
            409 => Response::ERR_NOORIGIN,
            411 => Response::ERR_NORECIPIENT,
            412 => Response::ERR_NOTEXTTOSEND,
            413 => Response::ERR_NOTOPLEVEL,
            414 => Response::ERR_WILDTOPLEVEL,
            415 => Response::ERR_BADMASK,
            417 => Response::ERR_INPUTTOOLONG,
            421 => Response::ERR_UNKNOWNCOMMAND,
            422 => Response::ERR_NOMOTD,
            423 => Response::ERR_NOADMININFO,
            424 => Response::ERR_FILEERROR,
            431 => Response::ERR_NONICKNAMEGIVEN,
            432 => Response::ERR_ERRONEOUSNICKNAME,
            433 => Response::ERR_NICKNAMEINUSE,
            436 => Response::ERR_NICKCOLLISION,
            437 => Response::ERR_UNAVAILRESOURCE,
            441 => Response::ERR_USERNOTINCHANNEL,
            442 => Response::ERR_NOTONCHANNEL,
            443 => Response::ERR_USERONCHANNEL,
            444 => Response::ERR_NOLOGIN,
            445 => Response::ERR_SUMMONDISABLED,
            446 => Response::ERR_USERSDISABLED,
            447 => Response::ERR_NONICKCHANGE,
            451 => Response::ERR_NOTREGISTERED,
            456 => Response::ERR_ACCEPTFULL,
            457 => Response::ERR_ACCEPTEXIST,
            458 => Response::ERR_ACCEPTNOT,
            461 => Response::ERR_NEEDMOREPARAMS,
            462 => Response::ERR_ALREADYREGISTERED,
            463 => Response::ERR_NOPERMFORHOST,
            464 => Response::ERR_PASSWDMISMATCH,
            465 => Response::ERR_YOUREBANNEDCREEP,
            466 => Response::ERR_YOUWILLBEBANNED,
            467 => Response::ERR_KEYSET,
            471 => Response::ERR_CHANNELISFULL,
            472 => Response::ERR_UNKNOWNMODE,
            473 => Response::ERR_INVITEONLYCHAN,
            474 => Response::ERR_BANNEDFROMCHAN,
            475 => Response::ERR_BADCHANNELKEY,
            476 => Response::ERR_BADCHANMASK,
            477 => Response::ERR_NEEDREGGEDNICK,
            478 => Response::ERR_BANLISTFULL,
            479 => Response::ERR_BADCHANNAME,
            481 => Response::ERR_NOPRIVILEGES,
            482 => Response::ERR_CHANOPRIVSNEEDED,
            483 => Response::ERR_CANTKILLSERVER,
            484 => Response::ERR_RESTRICTED,
            485 => Response::ERR_UNIQOPPRIVSNEEDED,
            489 => Response::ERR_SECUREONLYCHAN,
            491 => Response::ERR_NOOPERHOST,
            520 => Response::ERR_OPERONLY,
            501 => Response::ERR_UMODEUNKNOWNFLAG,
            502 => Response::ERR_USERSDONTMATCH,
            511 => Response::ERR_SILELISTFULL,
            524 => Response::ERR_HELPNOTFOUND,
            573 => Response::ERR_CANNOTSENDRP,
            635 => Response::ERR_NORULES,
            712 => Response::ERR_TOOMANYKNOCK,
            713 => Response::ERR_CHANOPEN,
            714 => Response::ERR_KNOCKONCHAN,
            723 => Response::ERR_NOPRIVS,
            734 => Response::ERR_MONLISTFULL,
            765 => Response::ERR_TARGETINVALID,
            766 => Response::ERR_NOMATCHINGKEY,
            767 => Response::ERR_KEYINVALID,
            768 => Response::ERR_KEYNOTSET,
            769 => Response::ERR_KEYNOPERMISSION,
            902 => Response::ERR_NICKLOCKED,
            904 => Response::ERR_SASLFAIL,
            905 => Response::ERR_SASLTOOLONG,
            906 => Response::ERR_SASLABORT,
            907 => Response::ERR_SASLALREADY,
            _ => return None,
        })
    }
}
