//! IRC success response code definitions (RPL_* numerics).
//!
//! This module contains the enum variants for non-error IRC server responses,
//! organized by category.

// This file is auto-generated from response/mod.rs refactoring.
// All RPL_* (success/reply) numeric codes.

use super::Response;

impl Response {
    /// Returns all RPL_* (success) response variants from code mapping.
    ///
    /// Used by `from_code()` to map numeric codes to Response enum variants.
    pub(super) fn from_success_code(code: u16) -> Option<Response> {
        Some(match code {
            1 => Response::RPL_WELCOME,
            2 => Response::RPL_YOURHOST,
            3 => Response::RPL_CREATED,
            4 => Response::RPL_MYINFO,
            5 => Response::RPL_ISUPPORT,
            10 => Response::RPL_BOUNCE,
            42 => Response::RPL_YOURID,
            200 => Response::RPL_TRACELINK,
            201 => Response::RPL_TRACECONNECTING,
            202 => Response::RPL_TRACEHANDSHAKE,
            203 => Response::RPL_TRACEUNKNOWN,
            204 => Response::RPL_TRACEOPERATOR,
            205 => Response::RPL_TRACEUSER,
            206 => Response::RPL_TRACESERVER,
            207 => Response::RPL_TRACESERVICE,
            208 => Response::RPL_TRACENEWTYPE,
            209 => Response::RPL_TRACECLASS,
            210 => Response::RPL_TRACERECONNECT,
            211 => Response::RPL_STATSLINKINFO,
            212 => Response::RPL_STATSCOMMANDS,
            216 => Response::RPL_STATSKLINE,
            219 => Response::RPL_ENDOFSTATS,
            220 => Response::RPL_STATSDLINE,
            221 => Response::RPL_UMODEIS,
            226 => Response::RPL_STATSSHUN,
            234 => Response::RPL_SERVLIST,
            235 => Response::RPL_SERVLISTEND,
            242 => Response::RPL_STATSUPTIME,
            243 => Response::RPL_STATSOLINE,
            249 => Response::RPL_STATSDEBUG,
            251 => Response::RPL_LUSERCLIENT,
            252 => Response::RPL_LUSEROP,
            253 => Response::RPL_LUSERUNKNOWN,
            254 => Response::RPL_LUSERCHANNELS,
            255 => Response::RPL_LUSERME,
            256 => Response::RPL_ADMINME,
            257 => Response::RPL_ADMINLOC1,
            258 => Response::RPL_ADMINLOC2,
            259 => Response::RPL_ADMINEMAIL,
            261 => Response::RPL_TRACELOG,
            262 => Response::RPL_TRACEEND,
            263 => Response::RPL_TRYAGAIN,
            265 => Response::RPL_LOCALUSERS,
            266 => Response::RPL_GLOBALUSERS,
            271 => Response::RPL_SILELIST,
            272 => Response::RPL_ENDOFSILELIST,
            276 => Response::RPL_WHOISCERTFP,
            281 => Response::RPL_ACCEPTLIST,
            282 => Response::RPL_ENDOFACCEPT,
            300 => Response::RPL_NONE,
            301 => Response::RPL_AWAY,
            302 => Response::RPL_USERHOST,
            303 => Response::RPL_ISON,
            305 => Response::RPL_UNAWAY,
            306 => Response::RPL_NOWAWAY,
            311 => Response::RPL_WHOISUSER,
            312 => Response::RPL_WHOISSERVER,
            313 => Response::RPL_WHOISOPERATOR,
            314 => Response::RPL_WHOWASUSER,
            315 => Response::RPL_ENDOFWHO,
            317 => Response::RPL_WHOISIDLE,
            318 => Response::RPL_ENDOFWHOIS,
            319 => Response::RPL_WHOISCHANNELS,
            321 => Response::RPL_LISTSTART,
            322 => Response::RPL_LIST,
            323 => Response::RPL_LISTEND,
            324 => Response::RPL_CHANNELMODEIS,
            325 => Response::RPL_UNIQOPIS,
            329 => Response::RPL_CREATIONTIME,
            330 => Response::RPL_WHOISACCOUNT,
            331 => Response::RPL_NOTOPIC,
            332 => Response::RPL_TOPIC,
            333 => Response::RPL_TOPICWHOTIME,
            335 => Response::RPL_WHOISBOT,
            338 => Response::RPL_WHOISACTUALLY,
            340 => Response::RPL_USERIP,
            341 => Response::RPL_INVITING,
            342 => Response::RPL_SUMMONING,
            346 => Response::RPL_INVITELIST,
            347 => Response::RPL_ENDOFINVITELIST,
            348 => Response::RPL_EXCEPTLIST,
            349 => Response::RPL_ENDOFEXCEPTLIST,
            351 => Response::RPL_VERSION,
            352 => Response::RPL_WHOREPLY,
            353 => Response::RPL_NAMREPLY,
            354 => Response::RPL_WHOSPCRPL,
            364 => Response::RPL_LINKS,
            365 => Response::RPL_ENDOFLINKS,
            366 => Response::RPL_ENDOFNAMES,
            367 => Response::RPL_BANLIST,
            368 => Response::RPL_ENDOFBANLIST,
            369 => Response::RPL_ENDOFWHOWAS,
            371 => Response::RPL_INFO,
            372 => Response::RPL_MOTD,
            374 => Response::RPL_ENDOFINFO,
            375 => Response::RPL_MOTDSTART,
            376 => Response::RPL_ENDOFMOTD,
            378 => Response::RPL_WHOISHOST,
            379 => Response::RPL_WHOISMODES,
            381 => Response::RPL_YOUREOPER,
            382 => Response::RPL_REHASHING,
            383 => Response::RPL_YOURESERVICE,
            391 => Response::RPL_TIME,
            392 => Response::RPL_USERSSTART,
            393 => Response::RPL_USERS,
            394 => Response::RPL_ENDOFUSERS,
            395 => Response::RPL_NOUSERS,
            396 => Response::RPL_HOSTHIDDEN,
            606 => Response::RPL_MAP,
            607 => Response::RPL_MAPEND,
            632 => Response::RPL_RULESTART,
            633 => Response::RPL_RULES,
            634 => Response::RPL_ENDOFRULES,
            646 => Response::RPL_STATSPLINE,
            670 => Response::RPL_STARTTLS,
            671 => Response::RPL_WHOISSECURE,
            691 => Response::ERR_STARTTLS,
            704 => Response::RPL_HELPSTART,
            705 => Response::RPL_HELPTXT,
            706 => Response::RPL_ENDOFHELP,
            710 => Response::RPL_KNOCK,
            711 => Response::RPL_KNOCKDLVR,
            728 => Response::RPL_QUIETLIST,
            729 => Response::RPL_ENDOFQUIETLIST,
            730 => Response::RPL_MONONLINE,
            731 => Response::RPL_MONOFFLINE,
            732 => Response::RPL_MONLIST,
            733 => Response::RPL_ENDOFMONLIST,
            760 => Response::RPL_WHOISKEYVALUE,
            761 => Response::RPL_KEYVALUE,
            900 => Response::RPL_LOGGEDIN,
            901 => Response::RPL_LOGGEDOUT,
            903 => Response::RPL_SASLSUCCESS,
            908 => Response::RPL_SASLMECHS,
            _ => return None,
        })
    }
}
